# Generated by Django 3.2 on 2021-04-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cam_Configer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pasw', models.CharField(max_length=32)),
                ('ip_address', models.CharField(max_length=150)),
                ('camera_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empolys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=150)),
                ('mobile_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Know',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=60)),
                ('dec', models.BooleanField()),
                ('data', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unknow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec', models.BooleanField()),
                ('data', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=200)),
            ],
        ),
    ]
