# Generated by Django 3.2 on 2021-04-11 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0002_cam_configer_empolys_know_unknow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='report',
        ),
        migrations.AlterField(
            model_name='know',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 4, 11, 13, 44, 2, 891919)),
        ),
        migrations.AlterField(
            model_name='unknow',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 11, 13, 44, 2, 892896)),
        ),
    ]
