# Generated by Django 3.2 on 2021-04-11 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0003_auto_20210411_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='know',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 4, 11, 13, 58, 27, 423059)),
        ),
        migrations.AlterField(
            model_name='know',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 11, 13, 58, 27, 423059)),
        ),
        migrations.AlterField(
            model_name='unknow',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 11, 13, 58, 27, 424034)),
        ),
    ]
