# Generated by Django 3.2 on 2021-04-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0004_auto_20210411_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='know',
            name='data',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='know',
            name='time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unknow',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
