# Generated by Django 3.2 on 2021-04-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0005_auto_20210411_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
                ('name2', models.CharField(max_length=50)),
            ],
        ),
    ]
