# Generated by Django 3.2 on 2021-04-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0006_cameraname'),
    ]

    operations = [
        migrations.AddField(
            model_name='know',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='know',
            name='data',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='know',
            name='dec',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='know',
            name='ids',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='know',
            name='time',
            field=models.CharField(default='', max_length=200),
        ),
    ]
