# Generated by Django 3.2 on 2021-04-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0007_auto_20210412_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='know',
            name='name',
        ),
        migrations.AddField(
            model_name='know',
            name='image',
            field=models.ImageField(default='', upload_to='static/stor'),
        ),
    ]
