# Generated by Django 3.2 on 2021-04-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0009_auto_20210413_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empolys',
            name='image',
            field=models.ImageField(default='', upload_to='static/stor/'),
        ),
    ]
