# Generated by Django 3.2 on 2021-04-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0010_alter_empolys_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cam_Configer2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pasw', models.CharField(max_length=32)),
                ('ip_address', models.CharField(max_length=150)),
                ('camera_number', models.CharField(max_length=20)),
            ],
        ),
    ]
