# Generated by Django 3.2 on 2021-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0011_cam_configer2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam_configer2',
            name='camera_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cam_configer2',
            name='ip_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cam_configer2',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cam_configer2',
            name='pasw',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
