# Generated by Django 3.2 on 2021-04-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0012_auto_20210415_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam_configer2',
            name='camera_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cam_configer2',
            name='ip_address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='cam_configer2',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='cam_configer2',
            name='pasw',
            field=models.CharField(default='', max_length=32),
        ),
    ]
