# Generated by Django 3.2 on 2021-04-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0014_auto_20210415_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cam_con',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Ip_address', models.CharField(max_length=100)),
                ('Camera_NO', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Cam_Configer2',
        ),
    ]
